services:

  # The rest api that serves tf object detection models
  tf-api:
    # container_name: tf-rest-api
    build:
      context: ./tf_api
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 5001:5001
    volumes:
      - ./asd:/asd
    networks:
      - vision-dep-net

  # The rest api that serves mmdetection models
  mmdetection-api:
    # container_name: mmdetection-rest-api
    build:
      context: ./mmdetection_api
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./asd:/asd
    networks:
      - vision-dep-net

  # Rest api that is used for deployment of models
  deployment-api:
    # container_name: deployment-api
    build:
      context: ./deployment_api
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 5003:5003
    networks:
      - vision-dep-net

  # Rest api used to make inference with deployed models
  inference-api:
    # container_name: inference-api
    build:
      context: ./inference_api
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    networks:
      - vision-dep-net

  # Postgresql container
  postgres:
    # container_name: postgres
    image: postgres:latest
    ports:
        - 5432:5432
    volumes:
      - ./postgres_volume:/postgres_volume
    environment:
        - POSTGRES_PASSWORD=1
    networks:
      - vision-dep-net

  # UI for postgresql db
  pgadmin4:
    # container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
        - 5050:80
    environment:
        PGADMIN_DEFAULT_EMAIL: "fburakbagci@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "1"
    networks:
      - vision-dep-net

  # Portainer allows us to accelerate container management by its UI
  container-manager-dev:
    # container_name: container-manager-dev
    image: portainer/portainer-ce
    # restart: always
    ports:
      - 18000:8000
      - 19000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      admin-password: fburakbagci@gmail.com
    networks:
      - vision-dep-net

# Docker network communicates services
networks:
  vision-dep-net:
    driver: bridge